language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: "c4hU2dMEqpPy6U4nDk8c9q3IGOHeIJJYgvmJmqroIYY32EsKvxdol3EP6LkBlI15fqOZFMiNGJHDYM9ApDGpPpAuC3Etue+RcTVp9CivYnqMfOTuth1aPNSuI9HktEcWg88nbPAwgTLKCBrDbPgXuxZOfK1acGgf6OqZvGYUzSIZ8GEFs7if/8XBJaCM/XE4VYLNQmQnwxVwcx9zV0NvXb+4PTm6NUqD4kPATjfWUV6sttL1hyd47uhrtfdUUR//PLas+C2ioEj9TptaIU4PkBlnszHkpsWgHl+KodJotpH5nW0LUopHKJNAUIYLEcPItMdgGXOrhdpEN5I7QUnJMOIlizu9mAfTLc6apxQjBut8zKdG6Y5NU8zEGEKu0RgMoj7WtpiWFajWU8IS+sPM2OVjjNY2T9b9mS6GlYbm/BS5ePGCUB+NBi+IV/aeG1LO21nQ3fE5D61bwSmhgK0RsrCV0C1lHmiCfbPE43j9obv6Kw+OgcIvQmUfBUdY8/oOVRJ9CHD7nKUmGKWolkVXGJ2RZsTKH/iI2ZofHm7Co01G1LQRx03MgUHd2ClMRSMA4OcJz6Nni92hgWbXRC9gbgHZZ0v4cj0msSW6t7UV/YsG1aT5WV+CntC7Uo9YUCFlVLNlRZ8KNM7sER2tAFbloQ7vlov1gdxgy82GnVefyMA="
  app: destination-node
  on:
    repo: Aaron-Lathrop/destination-node
