language: node_js
node_js: -"8.11.3"
deploy:
  provider: heroku
  api_key:
    secure: hiCS5RblSsyG6ZWKXjxLs2OLwpeHYWvzv6zsIY3VG1DwqBbcBMTcs3svyCsCTvsHu+7TZ8ea1fzIpUmwb1vikmItIQd53iYtKm4c0HRgvgI7UtEf5+LOsramVSaZGbZHbJSdxB+P+FfQRsq5zdIXNPNoyXPHylmxPdPcTTlviNiKRXhEWuxsWsjnxQNX0QMf6s0AT9wr2GnL8+OQ9Z52+dQX6tp5S/uUcKzzBdQDyVWbNFWT6lMOZUKNkJnACQ0RFSJbdV3UaFCBvcJOi2JiDtfIHaVp+tUBB9iAzlS1klQXyB5Wv69ELoTZ/MrqDfnRQXNKAlWQQXukaqr9sZ73o1ta9/FgPqkEjpddcYx9kJ5XsQiptaT9oxQnBS+idw2dwCVQLNN9nDBwqwoCG+wFNbtJ8Wz/rJyn7WwNhCRuta2vmu/08t8gqAI8eTWXObsTSBrGSxm0IwNHsgtn/CWZH0J+fuqR9CEPe6SrrDE0Lnx8g+r7ewFAvnXfTtcwdYWDuIHA+f+QsQ0n3cwqENpBGLyG05k7RbOVR2lrAsKkfcfRyb2M0OMgoR/c1AKdFIZpdSH0QCTo3Jbxw7Zp7XXTxMyGWiWh3z0FHWIs5lVlkRkAgYhhliSzgrQYoG26cBBoaE+hcdJyqpcHfnXz5ZCTGqo4E4uDkg6uZr+4xlVpHeM=
  app: destination-node
  on:
    repo: Aaron-Lathrop/destination-node
